version: '3'

services:
  postgres:
    container_name: "reperio-core-postgres"
    build: ./docker/db
    ports:
      - "54322:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - local
  redis:
    container_name: "reperio-core-redis"
    image: redis:4.0.11
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - local
      - reperio
  app:
    container_name: "reperio-core-app"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    networks:
      - local
      - reperio
    command: ["docker/app/start.sh"]
  maildev:
    container_name: "reperio-core-mail"
    image: "djfarrelly/maildev"
    ports:
      - "1080:80"
    networks:
      - local
      - reperio
volumes:
    data-volume:
    redis-data:

networks:
  local:
  reperio:
    external:
      name: reperio-network