version: '3'

services:
  postgres:
    image: postgres:10.4
    restart: always
    ports: 
      - "5432:5432"
    container_name: "reperio-postgres"
    volumes:
      - data-volume:/usr/local/pgsql/data
    build: ./docker-database/
  redis:
    image: redis:4.0.11
    restart: always
    ports:
      - "6379:6379"
    container_name: "reperio-redis"
    volumes:
      - redis-data:/data

volumes:
    data-volume:
    redis-data: